<edit rowscount="1" columnscount="4" >
    <cells>
        <cell row="0" column="1" >
                <component ctype="ValueEntry" Address="1"  leftnode="0" rightnode="-1"/>
        </cell>
        <cell row="0" column="2" >
                <component ctype="HWire"  leftnode="-1" rightnode="-1"/>
        </cell>
        <cell row="0" column="3" >
                <component ctype="Coil" Label="" Address="flbaixo"  leftnode="-1" rightnode="-1"/>
        </cell>
    </cells>
</edit>